# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fc63ed5c10182027ac732e0a546d85b9e19ebe6666b4fbd9000a9d791eb83e16d8df8492d5721f4fe95802fa9ad07cef1d2311ef33da13dc72c56b40ec3a405

test:
  secret_key_base: 94cf6a89ce79c9cf6526da82395ac94bbc67fe2343cffc7da89cf2aa294cd430255fe2d318ee172b12f66759bbb6386dae1c36ed121a417e8785afdc26910b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
